// Generated by dsh-gui whenever an update is available; regenerated by every
// check and removed automatically once no update remains. It runs fully
// detached from dsh-gui: first waits for the running dsh-gui and harness PIDs
// to exit (the shell kills the harness tree on shutdown), then fast-forwards
// the selected repositories to their remote default branch, rebuilds through
// `node scripts/dsh-gui.mjs build`, and relaunches dsh-gui.

import { spawn, spawnSync } from 'node:child_process'
import {
  appendFileSync,
  closeSync,
  existsSync,
  mkdirSync,
  openSync,
  readFileSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs'
import { basename, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = "__ROOT__";
const GUI_PID = __GUI_PID__;
const HARNESS_PID = __HARNESS_PID__;
const IS_WINDOWS = process.platform === 'win32';
const GUI_DIR = join(ROOT, '.dsh', 'gui');
const PLAN_FILE = join(GUI_DIR, 'pending-updates.json');
const LOG_FILE = join(GUI_DIR, 'update.log');
const SELF_PATH = fileURLToPath(import.meta.url);

// Rust copies this script to %TEMP%/dsh-gui-update-<pid>-<n>.mjs before
// executing it. Delete that temporary copy when this run finishes; the
// in-repo `.dsh/gui/update.mjs` copy is intentionally left alone.
function cleanupTempCopy() {
  if (!basename(SELF_PATH).startsWith('dsh-gui-update-')) return;
  try {
    unlinkSync(SELF_PATH);
  } catch {
    // Best effort: OS temp cleanup handles the rest.
  }
}

function bail(code) {
  cleanupTempCopy();
  process.exit(code);
}

function log(message) {
  const line = `[update] ${new Date().toISOString()} ${message}\n`;
  try {
    mkdirSync(GUI_DIR, { recursive: true });
    appendFileSync(LOG_FILE, line, 'utf8');
  } catch {
    // Best effort only: the inherited stderr handle also points at update.log.
  }
  // The Windows launcher runs this script inside a visible PowerShell console
  // (powershell -NoExit), so echo there too. On Unix the detached fallback
  // redirects stdout to the same log file, where echoing would just duplicate.
  if (IS_WINDOWS) {
    try {
      process.stdout.write(line);
    } catch {
      // Log file is still the authoritative copy if the console is gone.
    }
  }
}

function run(command, args, options = {}) {
  log(`$ ${command} ${args.join(' ')}`);
  const result = spawnSync(command, args, {
    cwd: options.cwd ?? ROOT,
    env: { ...process.env, ...(options.env ?? {}) },
    stdio: 'inherit',
    windowsHide: true,
    shell: false,
  });
  if (result.error) throw new Error(`failed to spawn ${command}: ${result.error.message}`);
  if (result.status !== 0) throw new Error(`${command} ${args.join(' ')} exited with code ${result.status}`);
}

let captureSeq = 0;

// Capture stdout through per-call files, never through 'pipe'. When dsh-gui
// was launched from a dsh sandbox session, the sandbox token rejects piped
// child stdio with EPERM while file handles and inherit/ignore work fine.
function capture(command, args, options = {}) {
  mkdirSync(GUI_DIR, { recursive: true });
  const id = `${process.pid}-${Date.now()}-${captureSeq++}`;
  const outPath = join(GUI_DIR, `git-capture-${id}.out`);
  const errPath = join(GUI_DIR, `git-capture-${id}.err`);
  let outFd;
  let errFd;
  try {
    outFd = openSync(outPath, 'w');
    errFd = openSync(errPath, 'w');
  } catch {
    return null;
  }
  try {
    const result = spawnSync(command, args, {
      cwd: options.cwd ?? ROOT,
      env: { ...process.env, GIT_TERMINAL_PROMPT: '0', ...(options.env ?? {}) },
      stdio: ['ignore', outFd, errFd],
      windowsHide: true,
      shell: false,
    });
    closeSync(outFd);
    closeSync(errFd);
    outFd = null;
    errFd = null;
    if (result.error || result.status !== 0) return null;
    return readFileSync(outPath, 'utf8').trim();
  } finally {
    if (outFd !== null) closeSync(outFd);
    if (errFd !== null) closeSync(errFd);
    try { unlinkSync(outPath); } catch { /* already gone */ }
    try { unlinkSync(errPath); } catch { /* already gone */ }
  }
}

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

function isAlive(pid) {
  if (!Number.isInteger(pid) || pid <= 0) return false;
  try {
    process.kill(pid, 0);
    return true;
  } catch (error) {
    // EPERM means the process exists but belongs to another user/session.
    return error && error.code === 'EPERM';
  }
}

async function waitForExit(pid, label, timeoutMs) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (!isAlive(pid)) {
      log(`${label} (pid ${pid}) exited`);
      return true;
    }
    await sleep(750);
  }
  log(`${label} (pid ${pid}) is still running after ${timeoutMs}ms`);
  return false;
}

function requestedIds(argv) {
  const index = argv.indexOf('--ids');
  if (index < 0 || index + 1 >= argv.length) return [];
  return String(argv[index + 1])
    .split(',')
    .map((value) => value.trim())
    .filter(Boolean);
}

function remoteDefaultBranch(dir) {
  const symrefs = capture('git', ['-C', dir, 'ls-remote', '--symref', 'origin', 'HEAD']) ?? '';
  for (const line of symrefs.split(/\r?\n/)) {
    const match = line.match(/^ref:\s+refs\/heads\/([^\t]+)\tHEAD$/);
    if (match && match[1]) return match[1];
  }
  const symbolic = capture('git', ['-C', dir, 'symbolic-ref', '--short', 'refs/remotes/origin/HEAD']);
  if (symbolic && symbolic.startsWith('origin/') && symbolic.length > 7) return symbolic.slice(7);
  throw new Error(`cannot resolve the remote default branch for ${dir}`);
}

function relaunch() {
  const exe = join(ROOT, IS_WINDOWS ? 'dsh-gui.exe' : 'dsh-gui');
  if (!existsSync(exe)) {
    log(`entry exe missing after update: ${exe}`);
    return;
  }
  log(`relaunching ${exe}`);
  const child = spawn(exe, [], {
    cwd: ROOT,
    detached: true,
    stdio: 'ignore',
    windowsHide: true,
  });
  child.on('error', (error) => log(`failed to relaunch: ${error.message}`));
  child.unref();
}

async function main() {
  log('=== update launcher started ===');

  if (!(await waitForExit(GUI_PID, 'dsh-gui', 180000))) {
    log('dsh-gui is still running; aborting so the exe checkout stays untouched');
    bail(2);
  }
  if (!(await waitForExit(HARNESS_PID, 'harness', 60000))) {
    log('harness is still running; aborting');
    bail(2);
  }

  let plan;
  try {
    plan = JSON.parse(readFileSync(PLAN_FILE, 'utf8'));
  } catch (error) {
    log(`cannot read ${PLAN_FILE}: ${error.message}`);
    bail(3);
  }
  const projects = Array.isArray(plan) ? plan : (plan.projects ?? []);
  const only = requestedIds(process.argv.slice(2));
  let targets = projects.filter((project) => project && project.behind && !project.error);
  if (only.length > 0) {
    targets = targets.filter((project) => only.includes(project.id));
  }
  if (targets.length === 0) {
    log('no pending updates selected; nothing to do');
    bail(0);
  }
  log(`updating: ${targets.map((project) => project.id).join(', ')}`);

  // Keep the plan honest while this detached process works: after a project is
  // reset it is marked done, so a crash/retry never re-runs a finished update
  // and only the still-pending submodules keep the badge alive after restart.
  function persistPlan() {
    writeFileSync(PLAN_FILE, JSON.stringify(plan, null, 2), 'utf8');
  }

  let updateOk = true;
  try {
    for (const project of targets) {
      const dir = project.path ? join(ROOT, project.path) : ROOT;
      if (!existsSync(dir)) {
        log(`[${project.id}] directory missing, skipping: ${dir}`);
        project.error = '目录不存在，无法更新';
        project.behind = false;
        persistPlan();
        continue;
      }
      log(`[${project.id}] fetching origin in ${dir}`);
      run('git', ['-C', dir, 'fetch', '--prune', 'origin'], { env: { GIT_TERMINAL_PROMPT: '0' } });
      const branch = remoteDefaultBranch(dir);
      log(`[${project.id}] resetting to origin/${branch}`);
      run('git', ['-C', dir, 'reset', '--hard', `origin/${branch}`]);
      if (project.path === '') {
        // The root checkout moved: bring every submodule to the commit the new
        // root revision records (later loop iterations then move submodules that
        // are individually behind to their own remote default branches).
        run('git', ['-C', ROOT, 'submodule', 'update', '--init', '--recursive']);
      }
      project.behind = false;
      project.error = null;
      persistPlan();
    }
  } catch (error) {
    updateOk = false;
    log(`git update failed, relaunching the previous exe: ${error.message}`);
  }

  if (updateOk) {
    log('rebuilding harness + entry exe + plugins');
    try {
      run(process.execPath, [join(ROOT, 'scripts', 'dsh-gui.mjs'), 'build'], {
        cwd: ROOT,
        env: { CI: 'true', DSH_HOME: join(ROOT, '.dsh') },
      });
    } catch (error) {
      log(`build failed, relaunching the previous exe: ${error.message}`);
    }
  }

  relaunch();
  log('=== update launcher finished ===');
}

try {
  await main();
  cleanupTempCopy();
} catch (error) {
  log(`update failed: ${error && error.stack ? error.stack : error}`);
  bail(1);
}
